Repository DroidKaigi/conference-app-2019, pull requests merged in 2019-01, with the labels that each got.

#227 Remove searchHintIcon
  feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SearchFragment.kt
  frontend/android/src/main/res/layout/activity_main.xml
  frontendcomponent/androidcomponent/src/main/res/values/themes.xml
Labels: awesome

#296 Fix to hide BottomAppBar when session detail can not scroll
  feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/SessionBottomAppBarBehavior.kt
  feature/session/src/main/res/layout/fragment_session_detail.xml
  feature/session/src/main/res/values/strings.xml
Labels: awesome

#293 Enable offline build on the CI
  .circleci/config.yml
  .circleci/scripts/retry_command
  build.gradle
  scripts/danger/Dangerfile.assertions
Labels: awesome

#300 Use Chrome Custom Tab for open url
  buildSrc/src/main/java/dependencies/Dep.kt
  feature/system/build.gradle
  feature/system/src/main/java/io/github/droidkaigi/confsched2019/system/actioncreator/ActivityActionCreator.kt
Labels: waiting for design

#303 Suppress Fragment replacement
  feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionPageFragment.kt
Labels: awesome

#331 Use Timber mpp
  buildSrc/src/main/java/dependencies/Dep.kt
  data/repository-impl/build.gradle
  ext/log/build.gradle
  ext/log/src/commonMain/kotlin/Logger.kt
  ext/log/src/commonMain/kotlin/io/github/droidkaigi/confsched2019/timber/Timber.kt
  feature/session/build.gradle
  feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/actioncreator/SessionContentsActionCreator.kt
  feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/SessionsItemDecoration.kt
  feature/sponsor/build.gradle
  feature/system/build.gradle
  feature/system/src/main/java/io/github/droidkaigi/confsched2019/system/actioncreator/ErrorHandler.kt
  frontend/android/build.gradle
  frontend/android/src/main/java/io/github/droidkaigi/confsched2019/App.kt
  frontend/android/src/main/java/io/github/droidkaigi/confsched2019/DebugApp.kt
Labels: awesome

#337 Add navigation drawer footer
  frontend/android/src/main/res/drawable/bg_navigation_footer.xml
  frontend/android/src/main/res/layout/activity_main.xml
  frontend/android/src/main/res/layout/layout_navigation_footer.xml
  frontend/android/src/main/res/menu/menu_nav_drawer.xml
  frontend/android/src/main/res/values-ja/strings.xml
  frontend/android/src/main/res/values/strings.xml
Labels: awesome

#342 Implemented session tab animation
  feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionPagesFragment.kt
  feature/session/src/main/res/color/selector_tab_title.xml
  feature/session/src/main/res/drawable/shape_pill_indicator.xml
  feature/session/src/main/res/layout/fragment_session_pages.xml
  feature/session/src/main/res/layout/layout_title_chip.xml
  feature/session/src/main/res/values/styles.xml
Labels: awesome

#308 Make some modules buildable for iOS Framework.
  buildSrc/src/main/java/dependencies/Dep.kt
  data/api-impl/build.gradle
  data/api-impl/src/commonMain/kotlin/io/github/droidkaigi/confsched2019/data/api/ApiEndpoint.kt
  data/api-impl/src/iosMain/kotlin/io/github/droidkaigi/confsched2019/data/api/ApiComponent.kt
  data/api-impl/src/iosMain/kotlin/io/github/droidkaigi/confsched2019/data/api/ApiEndpoint.kt
  data/api-impl/src/main/java/io/github/droidkaigi/confsched2019/data/api/ApiEndpoint.kt
  data/api-impl/src/main/java/io/github/droidkaigi/confsched2019/data/api/ApiModule.kt
  data/api/build.gradle
  data/db-room/build.gradle
  data/db/build.gradle
  data/firestore/build.gradle
  data/repository-impl/build.gradle
  data/repository/build.gradle
  ext/log/build.gradle
Labels: awesome

#326 use Maven Central mirror hosted on Google Cloud Storage for faster build
  build.gradle
  frontend/android/build.gradle
  frontendcomponent/androidcomponent/build.gradle
  frontendcomponent/androidtestcomponent/build.gradle
Labels: awesome

#364 Fix session list loading error caused because Dispatcher loses action
  frontendcomponent/androidcomponent/build.gradle
  frontendcomponent/androidcomponent/src/main/java/io/github/droidkaigi/confsched2019/dispatcher/Dispatcher.kt
  frontendcomponent/androidcomponent/src/test/java/io/github/droidkaigi/confsched2019/dispatcher/DispatcherTest.kt
Labels: awesome

#382 Draw line between time labels
  feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/SessionsItemDecoration.kt
  feature/session/src/main/res/values/dimens.xml
Labels: awesome

#422 Enable org.gradle.parallel for faster build
  gradle.properties
Labels: awesome

#441 Improve SessionsItemDecoration performance
  feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/SessionsItemDecoration.kt
Labels: awesome

#469 Show sessions in first view in iOS
  frontend/ios/.gitignore
  frontend/ios/Cartfile
  frontend/ios/Cartfile.resolved
  frontend/ios/DroidKaigi 2019.xcodeproj/project.pbxproj
  frontend/ios/DroidKaigi 2019/Base.lproj/Main.storyboard
  frontend/ios/DroidKaigi 2019/SessionRepository.swift
  frontend/ios/DroidKaigi 2019/SessionsViewController.swift
  frontend/ios/DroidKaigi 2019/SessionsViewModel.swift
  frontend/ios/DroidKaigi 2019/ViewController.swift
Labels: awesome

#504 Enable gzip compression when api calls
  data/api-impl/src/iosMain/kotlin/io/github/droidkaigi/confsched2019/data/api/ApiComponent.kt
  data/api-impl/src/main/java/io/github/droidkaigi/confsched2019/data/api/UserAgentInterceptor.kt
Labels: awesome

#602 Improve session survey screen
  feature/survey/build.gradle
  feature/survey/src/main/java/io/github/droidkaigi/confsched2019/survey/ui/SessionSurveyFragment.kt
  feature/survey/src/main/java/io/github/droidkaigi/confsched2019/survey/ui/bindingadapter/ViewBinding.kt
  feature/survey/src/main/java/io/github/droidkaigi/confsched2019/survey/ui/item/SpeakerIconItem.kt
  feature/survey/src/main/java/io/github/droidkaigi/confsched2019/survey/ui/widget/SurveyItem.kt
  feature/survey/src/main/res/drawable/ic_baseline_send_24px.xml
  feature/survey/src/main/res/drawable/submit_botton.xml
  feature/survey/src/main/res/layout/fragment_session_survey.xml
  feature/survey/src/main/res/layout/item_session_survey.xml
  feature/survey/src/main/res/layout/item_speaker_icon.xml
  feature/survey/src/main/res/values-ja/strings.xml
  feature/survey/src/main/res/values/arrays.xml
  feature/survey/src/main/res/values/strings.xml
  frontend/android/src/main/java/io/github/droidkaigi/confsched2019/ui/PageConfiguration.kt
Labels: high priority

#605 Fix SessionSurvey layout design
  feature/survey/src/main/java/io/github/droidkaigi/confsched2019/survey/ui/SessionSurveyFragment.kt
  feature/survey/src/main/res/drawable/background.xml
  feature/survey/src/main/res/layout/fragment_session_survey.xml
  feature/survey/src/main/res/layout/item_session_survey.xml
  frontend/android/src/main/AndroidManifest.xml
Labels: high priority

#604 MotionLayout for session detail title scrolling
  buildSrc/src/main/java/dependencies/Dep.kt
  feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/SessionDetailFragment.kt
  feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/CollapsibleToolbar.kt
  feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/SessionToolbarBehavior.kt
  feature/session/src/main/res/layout/fragment_session_detail.xml
  feature/session/src/main/res/xml/motion_session_detail.xml
Labels: awesome

#612 Draft TimeTableLayoutManager
  feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/TabularFormSessionPageFragment.kt
  feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/TabularFormSessionPagesFragment.kt
  feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/TabularServiceSessionItem.kt
  feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/TabularSpacerItem.kt
  feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/item/TabularSpeechSessionItem.kt
  feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/store/SessionPagesStore.kt
  feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/TimeTableDividerDecoration.kt
  feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/TimeTableLayoutManager.kt
  feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/TimeTableRoomLabelDecoration.kt
  feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/TimeTableTimeLabelDecoration.kt
  feature/session/src/main/res/layout/fragment_tabular_form_session_page.xml
  feature/session/src/main/res/layout/item_tabular_service_session.xml
  feature/session/src/main/res/layout/item_tabular_spacer.xml
  feature/session/src/main/res/layout/item_tabular_speech_session.xml
  feature/session/src/main/res/values/dimens.xml
  model/src/commonMain/kotlin/Room.kt
Labels: awesome

#601 [Proposal] Introduce Deferred for coroutines iOS API. and Fix network error handling issue.
  data/api-impl/src/commonMain/kotlin/io/github/droidkaigi/confsched2019/data/api/KtorDroidKaigiApi.kt
  data/api-impl/src/iosMain/kotlin/io/github/droidkaigi/confsched2019/data/api/ThrowableExt.kt
  data/api/build.gradle
  data/api/src/commonMain/kotlin/io/github/droidkaigi/confsched2019/data/api/DroidKaigiApi.kt
  frontend/ios/DroidKaigi 2019.xcodeproj/project.pbxproj
  frontend/ios/DroidKaigi 2019/Extensions/KotlinxDeferred+Extension.swift
  frontend/ios/DroidKaigi 2019/data/SessionRepository.swift
  frontend/ios/Podfile.lock
Labels: awesome

#670 Implement View Recycling on scrolling for TimeTableLayoutManager
  feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/TabularFormSessionPageFragment.kt
  feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/TimeTableDividerDecoration.kt
  feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/TimeTableLayoutManager.kt
  feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/TimeTableRoomLabelDecoration.kt
  feature/session/src/main/java/io/github/droidkaigi/confsched2019/session/ui/widget/TimeTableTimeLabelDecoration.kt
Labels: awesome

#552 Update Android Studio
  .idea/codeStyles/Project.xml
  README.md
  build.gradle
  buildSrc/src/main/java/dependencies/Dep.kt
  ext/android-extension/src/main/java/io/github/droidkaigi/confsched2019/ext/android/LifecycleExt.kt
  feature/floormap/src/main/res/layout/fragment_floor_map.xml
  feature/session/src/main/res/layout/fragment_bottom_sheet_sessions.xml
  frontend/ios/DroidKaigi 2019.xcodeproj/project.pbxproj
  frontend/ioscombined/build.gradle
  frontendcomponent/androidcomponent/build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: help wanted

#694 Add Adaptive Icon
  frontend/android/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  frontend/android/src/main/res/mipmap-hdpi-v26/ic_background.png
  frontend/android/src/main/res/mipmap-hdpi-v26/ic_foreground.png
  frontend/android/src/main/res/mipmap-mdpi-v26/ic_background.png
  frontend/android/src/main/res/mipmap-mdpi-v26/ic_foreground.png
  frontend/android/src/main/res/mipmap-xhdpi-v26/ic_background.png
  frontend/android/src/main/res/mipmap-xhdpi-v26/ic_foreground.png
  frontend/android/src/main/res/mipmap-xxhdpi-v26/ic_background.png
  frontend/android/src/main/res/mipmap-xxhdpi-v26/ic_foreground.png
  frontend/android/src/main/res/mipmap-xxxhdpi-v26/ic_background.png
  frontend/android/src/main/res/mipmap-xxxhdpi-v26/ic_foreground.png
Labels: awesome
